insert into books (title, author, description)
values ('The Master and Margarita', 'Mikhail Bulgakov',
        'A surreal classic about love, freedom, fear, and strange visitors in Moscow.'),
       ('1984', 'George Orwell',
        'A dystopian novel about surveillance, language, and a person under the pressure of a system.'),
       ('Harry Potter and the Philosopher''s Stone', 'J. K. Rowling',
        'The first story about a boy who discovers a hidden world of magic.'),
       ('Crime and Punishment', 'Fyodor Dostoevsky',
        'A psychological novel about guilt, punishment, and the search for redemption.'),
       ('Fahrenheit 451', 'Ray Bradbury',
        'A story about a world where books are forbidden and cultural memory becomes dangerous.'),
       ('The Midnight Library', 'Matt Haig',
        'A reflective novel about possible lives, regret, and choosing what matters.'),
       ('Dune', 'Frank Herbert',
        'A sweeping science fiction epic about power, ecology, prophecy, and survival on Arrakis.'),
       ('Circe', 'Madeline Miller', 'A lyrical retelling of myth through the voice of a witch finding her own power.'),
       ('The Hobbit', 'J. R. R. Tolkien', 'A cozy adventure about courage, treasure, dragons, and an unexpected hero.'),
       ('Pride and Prejudice', 'Jane Austen',
        'A sharp, elegant novel about manners, love, judgment, and self-knowledge.'),
       ('To Kill a Mockingbird', 'Harper Lee', 'A coming-of-age story about justice, empathy, and moral courage.'),
       ('The Great Gatsby', 'F. Scott Fitzgerald',
        'A glittering tragedy about longing, wealth, reinvention, and illusion.'),
       ('The Left Hand of Darkness', 'Ursula K. Le Guin',
        'A thoughtful science fiction novel about culture, gender, and trust.'),
       ('Project Hail Mary', 'Andy Weir', 'A hopeful space survival story driven by science, humor, and friendship.'),
       ('The Name of the Wind', 'Patrick Rothfuss',
        'A fantasy tale of talent, myth, music, and a legend telling his own story.'),
       ('Normal People', 'Sally Rooney', 'An intimate novel about connection, class, timing, and emotional honesty.'),
       ('The Song of Achilles', 'Madeline Miller',
        'A tender mythic love story set against the shadow of the Trojan War.'),
       ('Klara and the Sun', 'Kazuo Ishiguro',
        'A quiet speculative novel about devotion, observation, and what love might mean.'),
       ('Educated', 'Tara Westover',
        'A memoir about family, isolation, learning, and building a self through education.'),
       ('Atomic Habits', 'James Clear',
        'A practical guide to building better habits through small, repeatable systems.');

insert into users (id, username, email, password_hash, display_name)
values ('11111111-1111-4111-8111-111111111111', 'alice', 'alice@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Alice Morgan'),
       ('22222222-2222-4222-8222-222222222222', 'mark', 'mark@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Mark Rivers'),
       ('33333333-3333-4333-8333-333333333333', 'sofia', 'sofia@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Sofia Blake'),
       ('44444444-4444-4444-8444-444444444444', 'emma', 'emma@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Emma Stone'),
       ('55555555-5555-4555-8555-555555555555', 'liam', 'liam@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Liam Carter'),
       ('66666666-6666-4666-8666-666666666666', 'mia', 'mia@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Mia Harper'),
       ('77777777-7777-4777-8777-777777777777', 'noah', 'noah@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Noah Bennett'),
       ('88888888-8888-4888-8888-888888888888', 'olivia', 'olivia@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Olivia Reed'),
       ('99999999-9999-4999-8999-999999999999', 'ethan', 'ethan@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Ethan Brooks'),
       ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'ava', 'ava@bookly.local',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Ava Collins');

insert into user_books (user_id, book_id, user_rating, review)
select u.id, b.id, v.rating, v.review
from (values ('alice', 'The Master and Margarita', 5, 'A strange, brilliant book I keep thinking about.'),
             ('alice', '1984', 4, 'Bleak, precise, and still frighteningly sharp.'),
             ('mark', 'Harry Potter and the Philosopher''s Stone', 5, 'A warm beginning to a big adventure.'),
             ('mark', 'Crime and Punishment', 4, 'Difficult, intense, and absolutely worth it.'),
             ('sofia', 'Fahrenheit 451', 5, 'Short, bright, and unnervingly relevant.'),
             ('sofia', '1984', 3, 'A fascinating dystopia, though heavy in places.'),
             ('emma', 'The Midnight Library', 5, 'Tender, hopeful, and easy to recommend.'),
             ('emma', 'Circe', 5, 'Mythology with a pulse and a clear voice.'),
             ('liam', 'Dune', 5, 'Huge in scope and still incredibly controlled.'),
             ('liam', 'Project Hail Mary', 4, 'Fast, clever, and surprisingly warm.'),
             ('mia', 'Pride and Prejudice', 5, 'Witty, sharp, and beautifully balanced.'),
             ('mia', 'Normal People', 4, 'Quietly devastating in the best way.'),
             ('noah', 'The Hobbit', 5, 'Pure adventure comfort reading.'),
             ('noah', 'The Name of the Wind', 4, 'A magnetic voice and a rich world.'),
             ('olivia', 'The Song of Achilles', 5, 'Beautiful, intimate, and heartbreaking.'),
             ('olivia', 'Klara and the Sun', 4, 'Subtle, strange, and moving.'),
             ('ethan', 'Atomic Habits', 4, 'Very usable advice without too much noise.'),
             ('ethan', 'Educated', 5, 'A remarkable story of self-making.'),
             ('ava', 'The Left Hand of Darkness', 5, 'Elegant science fiction with real depth.'),
             ('ava', 'To Kill a Mockingbird', 4,
              'Simple on the surface, powerful underneath.')) as v(username, title, rating, review)
         join users u on u.username = v.username
         join books b on b.title = v.title;
